### ISSUE TITLE
Chainmesh/Nugget Crafting results

### ISSUE THREAD

**Issue by Pelirow** [AnonymousProductions/MineFantasy2#11]
Was able to craft every chain mesh and nugget except the three ultimate metals.

**Comment by AnonymousProductions** [comment]
The masterworks will have different recipes (since their made from 2 materials as you see in the texture)

**Comment by Pelirow** [comment]
The igno textures are green and yellow, which I assume is gold. The other two masterworks only have one color for the armors. Regardless, if masterworks won't have standard chain and nugget recipes, I'll close the issue.
