### ISSUE TITLE
When looked at with WAILA, Fireclay cruicble says its a stone crucible

### ISSUE THREAD

**Issue by Pelirow** [AnonymousProductions/MineFantasy2#13]

**Comment by AnonymousProductions** [comment]
WAILA?

**Comment by Pelirow** [comment]
What Am I Looking At. Very useful mod that helps with identifying blocks so you don't get them confused. I'll post a pic later so you can see.

**Comment by AnonymousProductions** [comment]
Sounds minor

**Comment by Pelirow** [comment]
Probably is, but very unusual for WAILA to do that so I was wondering if there was a chance the stone and fireclay crucibles had some code mixed up. I'll try to test sometime to see if anything comes up.

**Comment by AnonymousProductions** [comment]
Their just blocks and tile entities, could be the tile entity name id imagine

**Comment by AnonymousProductions** [comment]
Yeh Found the problem, Dealt with
