### ISSUE TITLE
Armor Rating in upper left corner

### ISSUE THREAD

**Issue by Pelirow** [AnonymousProductions/MineFantasy2#18]
Any way to toggle the information off?

**Comment by AnonymousProductions** [comment]
erm... don't think so, you can move it though

**Comment by Pelirow** [comment]
Toggle on/off option eventually would be a good idea, or at least a means of making the text smaller

**Comment by AnonymousProductions** [comment]
its not that in the way is it?

**Comment by Pelirow** [comment]
I'm just one voice, but it seems bigger than it needs to be to me. My deafness makes my eyes more valuable so I notice little things more than most, and I do have a 22inch monitor. Could be something to ask other beta testers just to get opinions. I have seen mods with overlays that allow for toggle on/off and for size change, which is why I suggested it.

**Comment by AnonymousProductions** [comment]
Im usually on full screen, not sure if the font can be smaller, I suppose it can be scaled
