### ISSUE TITLE
Blast Furnace eating unrefined ingots

### ISSUE THREAD

**Issue by Pelirow** [AnonymousProductions/MineFantasy2#20]
Haven't tested with other stuff, but I have a blast furnace with just two furnace chambers. They work great when one type of ingot is used, but I tested smelting one unrefined black steel ingot and one unrefined red steel ingot and only one of the two gets output into the crucible under the heater. The other gets eaten. Intended?

**Comment by AnonymousProductions** [comment]
Yeh they don't like mixing... buutt.. not really a major issue since it punishes messy users...

**Comment by Pelirow** [comment]
There's no warning that blasting multiple metals in different chambers is "messy." The big furnace from 1.6.4 could smelt four different things, no reason to think otherwise for the blast chambers. Probably good to put a little hint on the blast chamber pages about it being unwise for a blacksmith to mingle metals in the furnace.

**Comment by AnonymousProductions** [comment]
Probably, it only having 1 slot and 1 accessible chamber is a clue, just when smelting: it has to try and keep track on all the chambers above it, and it only keeps track of 1 result

**Comment by AnonymousProductions** [comment]
you sure about that?... It works fine and just ignores mismatched inputs, did just a 2 block furnace: 1 iron 1 blue steel, it made whatever was on the lower chamber and didnt consume the top neither smelted. so far as it seems its fine...

**Comment by Pelirow** [comment]
I'm sure. My blast furnaces in my test world are all malfunctioning once mismatched ingots are put in and the topmost ingot is getting eaten. Breaking and replacing the blast furnace seems to make it worse- now when I make two block furnaces in the exact same location, half the time I smelt identical unrefined ingots in the two chambers, the topmost chamber causes the whole blast furnace to malfunction- no smoke particles and no smelting occurs. Breaking the topmost chamber allows the chamber below it to start putting out particles but doesn't always smelt the ingot and coal still in the chamber.

Are you testing in a dev environment or in an actual world? Have you tried breaking the blast furnace and placing it in the exact same location? Have you tried mixing all three unrefined red/blue/black steel ingots instead of iron?

I have about 50 other mods thrown into the test world to see if things break, but I really can't think of anything in any of the other mods that'd break your blast furnace, unless somehow your blast furnace code and Railcraft's blast furnace code are fighting.

Will test in a fresh world with just MF2, but it definitely seems that the longer a blast furnace exists in a world in one particular spot and is used, the more it malfunctions.

Are you using the version of MF2 you most recently linked for fixing the SMP issues? That's the one I'm using now.

**Comment by Pelirow** [comment]
Been doing more testing in my test world with two different blast furnaces and they still randomly stop working or eating ingots in various orders/amounts/variety of inputs, but it seems once I place a small stone chimney on top of both blast furnaces, all issues stop and stuff processes as intended.

**Comment by Pelirow** [comment]
Nope, still getting eaten. 

I was testing putting three pieces of unrefined black ingots in the furnace with 2 coal. The first two unrefined ingots would output fine, and the third ingot would work its way down to the bottom chamber without coal. Left it in there to see if it would get eaten alone, since the blast furnace heater was still working and the top was spewing smoke. Nope, still there. Added in a piece of coal and it worked its way down to the bottom chamber that had the unrefined ingot and put more coal in the heater, at least 10 pieces, and there was no output after the heater went through all ten pieces of coal I put in it. Put in two unrefined ingots of a different color and 2 coal with them in the chambers, and immediately they smelted, as if the burn time for the eaten unrefined ingot was transferred to the new ones.

Just one example of 5 or 6 different ways that seem to break the blast furnace.

**Comment by AnonymousProductions** [comment]
when "consuming the top item" are you sure its not just falling down the chute, because that's all I'm getting

**Comment by AnonymousProductions** [comment]
Finally Started to get this problem.. Dealt with it too
