### ISSUE TITLE
Bonemeal on grass produces berry bushes

### ISSUE THREAD

**Issue by Pelirow** [AnonymousProductions/MineFantasy2#21]

**Comment by AnonymousProductions** [comment]
Yeh its ment to

**Comment by Pelirow** [comment]
Well, that'd make exploration for berry bushes less fun, and make it easier to RNG for juicy berries by mass spamming bonemeal.

**Comment by AnonymousProductions** [comment]
Suppose, could make it rarer, just makes it renewable this way

**Comment by Pelirow** [comment]
Mmm, okay. I like the non-renewability of the bushes, makes them commodities, possibly for trading too. They are supposed to be picked up by shears, yes?

**Comment by AnonymousProductions** [comment]
hm.. suppose, the bushes regenerate berries anyway
