### ISSUE TITLE
Blue Steel diamond dust necessary?

### ISSUE THREAD

**Issue by Pelirow** [AnonymousProductions/MineFantasy2#23]
Is there a use for diamond dust other than blue steel? If no, why not just use lapis? Red steel is per se "cheaper" since it uses redstone dust.

**Comment by AnonymousProductions** [comment]
mostly a cost balance, lapis is just stupid so I dont really care about using it. but I havent played round with it that much to see how balanced it is yet

**Comment by Pelirow** [comment]
I've been ignoring blue steel in favor of red. When MFII is played alone or with few mods, it isn't much of a cost; in modsets where diamonds also have uses elsewhere, there's little functional reason to make blue steel over red because red is cheaper, regardless of the higher enchantability. 

It's gonna be hard enough getting red/blue steel equipment, pretty sure people would rather use books on such equipment than leave up their strongest equipment to the RNG. Basically the same issue with the encrusted armors- great in principle, not so much in balance.

I understand lapis feeling stupid, which is why I like it when it actually has a viable use. lapis is rarer than redstone, too.

**Comment by AnonymousProductions** [comment]
Blue steel is lighter however, less stamina decay

could either use lapis-la-uselessy or give more diamond dust, I may just use lapis then
