### ISSUE TITLE
Reach of some weapons

### ISSUE THREAD

**Issue by Pelirow** [AnonymousProductions/MineFantasy2#24]
I notice the lance, spear, and, halberd have reaches of +2 and better, but the greatsword, battleaxe, and warhammer don't have any extended reach. Shouldn't they at least have a reach of +1 or +1.5?

**Comment by AnonymousProductions** [comment]
well reach is a silly thing id wish to avoid using if I could.

**Comment by Pelirow** [comment]
Why? It's a mechanic that adds a nice layer to your weapons. There's no point in having all the weapons if they don't have distinctively different advantages, and the combination of reach, damage, and blunt/slashing makes the variety worthwhile. 

Just seems odd that a greatsword and a normal sword have the same range. You already have the code for the longest weapons, doesn't seem like it would be too hard to change for the mid-range weapons.

**Comment by AnonymousProductions** [comment]
it's messy, doesn't discriminate on why you swing, open a door and BAM you hit an enemy, it gets kind of annoying after awhile. and I don''t trust it to work all the time even though it appears so

Ill add it, and get rid of it if it gets annoying

**Comment by Pelirow** [comment]
Since I suggested it, I'll try to test it as much as I can against short and longer range on a 1-2-3-4 block range of attacking and whatnot
