### ISSUE TITLE
missing updated wiki?

### ISSUE THREAD

**Issue by k1r0s** [AnonymousProductions/MineFantasy2#29]
I just downloaded mf2 alpha 2.4.5

Im looking for a updated wiki, or at least info about the BASICS.

If you are looking for a co-developer i can help you, i have experience with java but none with mc forge api. If you teach me the basics i can help you a lot with bugs, etc. 

I really love this mod, i would like help you to improve it  :)

**Comment by k1r0s** [comment]
i saw many videos but neither of thus where about my version :S

I guess i need a hammer to craft bronze pickaxe but how? xD

**Comment by AnonymousProductions** [comment]
there should be a book you start off with. that has information
