### ISSUE TITLE
Bandage appears to do nothing

### ISSUE THREAD

**Issue by Pelirow** [AnonymousProductions/MineFantasy2#7]
Held a strong bandage, used right click, there was a motion as if applying the bandage but nothing happened.

**Comment by AnonymousProductions** [comment]
hold down for awhile and it restores health, doesnt work when on fire or taking environmental damage and can be interrupted

**Comment by Pelirow** [comment]
Confirmed success with the strong bandage. Had to hold it down much longer than I expected.
